// Fleet catalog, generated from official Kruizly Excel Fleet Master
// Categories: economy (sedans & hatchbacks), suv, mpv, luxury.
// All driver rates: ₹2,000 / day.
// Loaded as a plain classic script (no bundler) so fleet.js, booking.js,
// and vehicle-gallery.js can reference fleetVehicles directly.

const fleetVehicles = [
  {
    "id": "krz-01",
    "slug": "bmw-520d-diesel-automatic",
    "regNo": "",
    "brand": "BMW",
    "model": "520D",
    "year": 2017,
    "category": "luxury",
    "icon": "🚘",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 18000,
    "priceHour": 750,
    "driverPrice": 2000,
    "securityDeposit": 15000,
    "freeKm": 250,
    "extraKm": 60,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-02",
    "slug": "mahindra-7xo-diesel-amt",
    "regNo": "",
    "brand": "Mahindra",
    "model": "7XO",
    "year": 2026,
    "category": "suv",
    "icon": "🚙",
    "transmission": "AMT",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 9000,
    "priceHour": 375,
    "driverPrice": 2000,
    "securityDeposit": 7000,
    "freeKm": 250,
    "extraKm": 28,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-03",
    "slug": "tata-altroz-petrol-manual",
    "regNo": "",
    "brand": "Tata",
    "model": "Altroz",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-04",
    "slug": "tata-altroz-petrol-cng-manual",
    "regNo": "",
    "brand": "Tata",
    "model": "Altroz",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-05",
    "slug": "hyundai-aura-petrol-amt",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Aura",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-06",
    "slug": "hyundai-aura-petrol-cng-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Aura",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-07",
    "slug": "maruti-suzuki-baleno-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Baleno",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-08",
    "slug": "maruti-suzuki-brezza-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Brezza",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-09",
    "slug": "maruti-suzuki-brezza-diesel-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Brezza",
    "year": 2018,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4000,
    "priceHour": 167,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-10",
    "slug": "kia-carens-diesel-manual",
    "regNo": "",
    "brand": "Kia",
    "model": "Carens",
    "year": 2025,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-11",
    "slug": "jeep-compass-diesel-manual",
    "regNo": "",
    "brand": "Jeep",
    "model": "Compass",
    "year": 2020,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-12",
    "slug": "hyundai-creta-diesel-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Creta",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 3500,
    "freeKm": 250,
    "extraKm": 14,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-13",
    "slug": "maruti-suzuki-dzire-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Dzire",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-14",
    "slug": "maruti-suzuki-ertiga-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Ertiga",
    "year": 2025,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 3300,
    "priceHour": 138,
    "driverPrice": 2000,
    "securityDeposit": 3500,
    "freeKm": 250,
    "extraKm": 14,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-15",
    "slug": "hyundai-exter-petrol-amt",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Exter",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-16",
    "slug": "hyundai-exter-petrol-cng-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Exter",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2800,
    "priceHour": 117,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-17",
    "slug": "maruti-suzuki-fronx-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Fronx",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-18",
    "slug": "maruti-suzuki-fronx-petrol-automatic",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Fronx",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2700,
    "priceHour": 113,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-19",
    "slug": "toyota-glanza-petrol-cng-manual",
    "regNo": "",
    "brand": "Toyota",
    "model": "Glanza",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-20",
    "slug": "maruti-suzuki-grand-vitara-diesel-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Grand Vitara",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4000,
    "priceHour": 167,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-21",
    "slug": "hyundai-i20-petrol-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "i20",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-22",
    "slug": "hyundai-i20-diesel-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "i20",
    "year": 2018,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3000,
    "priceHour": 125,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-23",
    "slug": "maruti-suzuki-ignis-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Ignis",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-24",
    "slug": "toyota-innova-crysta-diesel-manual",
    "regNo": "",
    "brand": "Toyota",
    "model": "Innova Crysta",
    "year": 2017,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-25",
    "slug": "toyota-innova-crysta-diesel-automatic",
    "regNo": "",
    "brand": "Toyota",
    "model": "Innova Crysta",
    "year": 2018,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-26",
    "slug": "tata-nexon-petrol-cng-manual",
    "regNo": "",
    "brand": "Tata",
    "model": "Nexon",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3000,
    "priceHour": 125,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-27",
    "slug": "tata-punch-petrol-cng-manual",
    "regNo": "",
    "brand": "Tata",
    "model": "Punch",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2700,
    "priceHour": 113,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-28",
    "slug": "tata-safari-diesel-automatic",
    "regNo": "",
    "brand": "Tata",
    "model": "Safari",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 9000,
    "priceHour": 375,
    "driverPrice": 2000,
    "securityDeposit": 7000,
    "freeKm": 250,
    "extraKm": 28,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-29",
    "slug": "mahindra-scorpio-n-diesel-manual",
    "regNo": "",
    "brand": "Mahindra",
    "model": "Scorpio N",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-30",
    "slug": "maruti-suzuki-swift-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Swift",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-31",
    "slug": "maruti-suzuki-swift-petrol-amt",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Swift",
    "year": 2021,
    "category": "economy",
    "icon": "🚗",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-32",
    "slug": "mahindra-thar-diesel-manual",
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 4,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-33",
    "slug": "mahindra-thar-diesel-automatic",
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 4,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-34",
    "slug": "mahindra-thar-roxx-diesel-automatic",
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar Roxx",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 7000,
    "priceHour": 292,
    "driverPrice": 2000,
    "securityDeposit": 5000,
    "freeKm": 250,
    "extraKm": 20,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-35",
    "slug": "maruti-suzuki-wagonr-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "WagonR",
    "year": 2023,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2300,
    "priceHour": 96,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-36",
    "slug": "maruti-suzuki-xl6-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "XL6",
    "year": 2023,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-37",
    "slug": "mahindra-xuv500-diesel-manual",
    "regNo": "",
    "brand": "Mahindra",
    "model": "XUV500",
    "year": 2022,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-38",
    "slug": "mahindra-xuv700-diesel-manual",
    "regNo": "",
    "brand": "Mahindra",
    "model": "XUV700",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  }
];

// Image path resolution: map vehicle brand + model to asset files.
const fleetImageOverrides = {
  "Hyundai Exter": "assets/fleet/Hyundai Exter .png",
  "Mahindra XUV700": "assets/fleet/Mahindra XUV700 .png",
  "Tata Altroz": "assets/fleet/Tata Altroz .png",
  "Toyota Urban Cruiser": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "Toyota Urban Cruiser Taisor": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "Mahindra Thar Roxx": "assets/fleet/Thar Roxx.avif",
  "BMW 520D": "assets/fleet/BMW 520D.png",
};

function fleetImagePath(vehicle) {
  if (!vehicle) return "assets/favicon.svg";
  const fullName = `${vehicle.brand} ${vehicle.model}`.trim();
  const rawPath = fleetImageOverrides[fullName] || `assets/fleet/${fullName}.png`;
  return encodeURI(rawPath);
}

function getFleetVehicle(query) {
  if (!query || query === "undefined" || query === "null") return fleetVehicles[0] || null;
  const q = String(query).trim().toLowerCase();
  return (
    fleetVehicles.find(
      (v) =>
        (v.id && v.id.toLowerCase() === q) ||
        (v.slug && v.slug.toLowerCase() === q) ||
        (v.regNo && v.regNo.toLowerCase() === q) ||
        `${v.brand} ${v.model}`.toLowerCase() === q ||
        `${v.brand}-${v.model}`.toLowerCase().replace(/\s+/g, "-") === q ||
        v.brand.toLowerCase() === q ||
        v.model.toLowerCase() === q
    ) || fleetVehicles[0] || null
  );
}

if (typeof window !== "undefined") {
  window.fleetImagePath = fleetImagePath;
  window.fleetVehicles = fleetVehicles;
  window.getFleetVehicle = getFleetVehicle;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = { fleetVehicles, fleetImagePath, getFleetVehicle };
}
