// Fleet catalog, generated from official Kruizly Excel Fleet Master: D:\\AYAN\\Excel\\Car Fleet Details CRP.xlsx
// Categories: economy (sedans & hatchbacks), suv, mpv, luxury.
// All driver rates: ₹2,000 / day.
// Loaded as a plain classic script (no bundler) so fleet.js, booking.js,
// and vehicle-gallery.js can reference `fleetVehicles` directly.

const fleetVehicles = [
  {
    "regNo": "",
    "brand": "BMW",
    "model": "520D",
    "year": 2017,
    "category": "luxury",
    "icon": "🚘",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 18000,
    "priceHour": 750,
    "driverPrice": 2000,
    "securityDeposit": 15000,
    "freeKm": 250,
    "extraKm": 60,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Mahindra",
    "model": "7XO",
    "year": 2026,
    "category": "suv",
    "icon": "🚙",
    "transmission": "AMT",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 9000,
    "priceHour": 375,
    "driverPrice": 2000,
    "securityDeposit": 7000,
    "freeKm": 250,
    "extraKm": 28,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Tata",
    "model": "Altroz",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Tata",
    "model": "Altroz",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Hyundai",
    "model": "Aura",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Hyundai",
    "model": "Aura",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Baleno",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Brezza",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Brezza",
    "year": 2018,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4000,
    "priceHour": 167,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Kia",
    "model": "Carens",
    "year": 2025,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Jeep",
    "model": "Compass",
    "year": 2020,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Hyundai",
    "model": "Creta",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 3500,
    "freeKm": 250,
    "extraKm": 14,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Dzire",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Ertiga",
    "year": 2025,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 3300,
    "priceHour": 138,
    "driverPrice": 2000,
    "securityDeposit": 3500,
    "freeKm": 250,
    "extraKm": 14,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Hyundai",
    "model": "Exter",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Hyundai",
    "model": "Exter",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2800,
    "priceHour": 117,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Fronx",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Fronx",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2700,
    "priceHour": 113,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Toyota",
    "model": "Glanza",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Grand Vitara",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4000,
    "priceHour": 167,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Hyundai",
    "model": "i20",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Hyundai",
    "model": "i20",
    "year": 2018,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3000,
    "priceHour": 125,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Ignis",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Toyota",
    "model": "Innova Crysta",
    "year": 2017,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Toyota",
    "model": "Innova Crysta",
    "year": 2018,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Tata",
    "model": "Nexon",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3000,
    "priceHour": 125,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Tata",
    "model": "Punch",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2700,
    "priceHour": 113,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Tata",
    "model": "Safari",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 9000,
    "priceHour": 375,
    "driverPrice": 2000,
    "securityDeposit": 7000,
    "freeKm": 250,
    "extraKm": 28,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Mahindra",
    "model": "Scorpio N",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Swift",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Swift",
    "year": 2021,
    "category": "economy",
    "icon": "🚗",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 4,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 4,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar Roxx",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 7000,
    "priceHour": 292,
    "driverPrice": 2000,
    "securityDeposit": 5000,
    "freeKm": 250,
    "extraKm": 20,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "WagonR",
    "year": 2023,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2300,
    "priceHour": 96,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "XL6",
    "year": 2023,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Mahindra",
    "model": "XUV500",
    "year": 2022,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "regNo": "",
    "brand": "Mahindra",
    "model": "XUV700",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  }
];

// Image path resolution: map vehicle brand + model to asset files.
const fleetImageOverrides = {
  "Hyundai Exter": "assets/fleet/Hyundai Exter .png",
  "Mahindra XUV700": "assets/fleet/Mahindra XUV700 .png",
  "Tata Altroz": "assets/fleet/Tata Altroz .png",
  "Toyota Urban Cruiser": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "Toyota Urban Cruiser Taisor": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "Mahindra Thar Roxx": "assets/fleet/Thar Roxx.avif",
  "BMW 520D": "assets/fleet/BMW 520D.png",
};

function fleetImagePath(vehicle) {
  if (!vehicle) return "assets/favicon.svg";
  const fullName = `${vehicle.brand} ${vehicle.model}`.trim();
  const rawPath = fleetImageOverrides[fullName] || `assets/fleet/${fullName}.png`;
  return encodeURI(rawPath);
}

if (typeof window !== "undefined") {
  window.fleetImagePath = fleetImagePath;
  window.fleetVehicles = fleetVehicles;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = { fleetVehicles, fleetImagePath };
}
