// Fleet catalog, generated from official Kruizly Excel Fleet Master
// Categories: economy (sedans & hatchbacks), suv, mpv, luxury.
// All driver rates: ₹2,000 / day.
// Loaded as a plain classic script (no bundler) so fleet.js, booking.js,
// and vehicle-gallery.js can reference fleetVehicles directly.

const fleetVehicles = [
  {
    "id": "krz-01",
    "slug": "bmw-520d-diesel-automatic",
    "regNo": "",
    "brand": "BMW",
    "model": "520D",
    "year": 2017,
    "category": "luxury",
    "icon": "🚘",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 18000,
    "priceHour": 750,
    "driverPrice": 2000,
    "securityDeposit": 15000,
    "freeKm": 250,
    "extraKm": 60,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-02",
    "slug": "mahindra-7xo-diesel-amt",
    "regNo": "",
    "brand": "Mahindra",
    "model": "7XO",
    "year": 2026,
    "category": "suv",
    "icon": "🚙",
    "transmission": "AMT",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 9000,
    "priceHour": 375,
    "driverPrice": 2000,
    "securityDeposit": 7000,
    "freeKm": 250,
    "extraKm": 28,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-03",
    "slug": "tata-altroz-petrol-manual",
    "regNo": "",
    "brand": "Tata",
    "model": "Altroz",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-04",
    "slug": "tata-altroz-petrol-cng-manual",
    "regNo": "",
    "brand": "Tata",
    "model": "Altroz",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-05",
    "slug": "hyundai-aura-petrol-amt",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Aura",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-06",
    "slug": "hyundai-aura-petrol-cng-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Aura",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-07",
    "slug": "maruti-suzuki-baleno-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Baleno",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-08",
    "slug": "maruti-suzuki-brezza-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Brezza",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-09",
    "slug": "maruti-suzuki-brezza-diesel-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Brezza",
    "year": 2018,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4000,
    "priceHour": 167,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-10",
    "slug": "kia-carens-diesel-manual",
    "regNo": "",
    "brand": "Kia",
    "model": "Carens",
    "year": 2025,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-11",
    "slug": "jeep-compass-diesel-manual",
    "regNo": "",
    "brand": "Jeep",
    "model": "Compass",
    "year": 2020,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-12",
    "slug": "hyundai-creta-diesel-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Creta",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 3500,
    "freeKm": 250,
    "extraKm": 14,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-13",
    "slug": "maruti-suzuki-dzire-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Dzire",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-14",
    "slug": "maruti-suzuki-ertiga-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Ertiga",
    "year": 2025,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 3300,
    "priceHour": 138,
    "driverPrice": 2000,
    "securityDeposit": 3500,
    "freeKm": 250,
    "extraKm": 14,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-15",
    "slug": "hyundai-exter-petrol-amt",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Exter",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-16",
    "slug": "hyundai-exter-petrol-cng-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "Exter",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2800,
    "priceHour": 117,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-17",
    "slug": "maruti-suzuki-fronx-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Fronx",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-18",
    "slug": "maruti-suzuki-fronx-petrol-automatic",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Fronx",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2700,
    "priceHour": 113,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-19",
    "slug": "toyota-glanza-petrol-cng-manual",
    "regNo": "",
    "brand": "Toyota",
    "model": "Glanza",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-20",
    "slug": "maruti-suzuki-grand-vitara-diesel-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Grand Vitara",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 4000,
    "priceHour": 167,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-21",
    "slug": "hyundai-i20-petrol-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "i20",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2600,
    "priceHour": 108,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-22",
    "slug": "hyundai-i20-diesel-manual",
    "regNo": "",
    "brand": "Hyundai",
    "model": "i20",
    "year": 2018,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3000,
    "priceHour": 125,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-23",
    "slug": "maruti-suzuki-ignis-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Ignis",
    "year": 2024,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-24",
    "slug": "toyota-innova-crysta-diesel-manual",
    "regNo": "",
    "brand": "Toyota",
    "model": "Innova Crysta",
    "year": 2017,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-25",
    "slug": "toyota-innova-crysta-diesel-automatic",
    "regNo": "",
    "brand": "Toyota",
    "model": "Innova Crysta",
    "year": 2018,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-26",
    "slug": "tata-nexon-petrol-cng-manual",
    "regNo": "",
    "brand": "Tata",
    "model": "Nexon",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 3000,
    "priceHour": 125,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-27",
    "slug": "tata-punch-petrol-cng-manual",
    "regNo": "",
    "brand": "Tata",
    "model": "Punch",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2700,
    "priceHour": 113,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-28",
    "slug": "tata-safari-diesel-automatic",
    "regNo": "",
    "brand": "Tata",
    "model": "Safari",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 9000,
    "priceHour": 375,
    "driverPrice": 2000,
    "securityDeposit": 7000,
    "freeKm": 250,
    "extraKm": 28,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-29",
    "slug": "mahindra-scorpio-n-diesel-manual",
    "regNo": "",
    "brand": "Mahindra",
    "model": "Scorpio N",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-30",
    "slug": "maruti-suzuki-swift-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Swift",
    "year": 2025,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-31",
    "slug": "maruti-suzuki-swift-petrol-amt",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "Swift",
    "year": 2021,
    "category": "economy",
    "icon": "🚗",
    "transmission": "AMT",
    "fuel": "Petrol",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2500,
    "priceHour": 104,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-32",
    "slug": "mahindra-thar-diesel-manual",
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 4,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-33",
    "slug": "mahindra-thar-diesel-automatic",
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar",
    "year": 2024,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 4,
    "bags": 2,
    "available": 1,
    "priceDay": 5500,
    "priceHour": 229,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-34",
    "slug": "mahindra-thar-roxx-diesel-automatic",
    "regNo": "",
    "brand": "Mahindra",
    "model": "Thar Roxx",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 7000,
    "priceHour": 292,
    "driverPrice": 2000,
    "securityDeposit": 5000,
    "freeKm": 250,
    "extraKm": 20,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-35",
    "slug": "maruti-suzuki-wagonr-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "WagonR",
    "year": 2023,
    "category": "economy",
    "icon": "🚗",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 5,
    "bags": 2,
    "available": 1,
    "priceDay": 2300,
    "priceHour": 96,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-36",
    "slug": "maruti-suzuki-xl6-petrol-cng-manual",
    "regNo": "",
    "brand": "Maruti Suzuki",
    "model": "XL6",
    "year": 2023,
    "category": "mpv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Petrol + CNG",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 3500,
    "priceHour": 146,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-37",
    "slug": "mahindra-xuv500-diesel-manual",
    "regNo": "",
    "brand": "Mahindra",
    "model": "XUV500",
    "year": 2022,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 4500,
    "priceHour": 188,
    "driverPrice": 2000,
    "securityDeposit": 3000,
    "freeKm": 250,
    "extraKm": 12,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  },
  {
    "id": "krz-38",
    "slug": "mahindra-xuv700-diesel-manual",
    "regNo": "",
    "brand": "Mahindra",
    "model": "XUV700",
    "year": 2025,
    "category": "suv",
    "icon": "🚙",
    "transmission": "Manual",
    "fuel": "Diesel",
    "seats": 7,
    "bags": 2,
    "available": 1,
    "priceDay": 6000,
    "priceHour": 250,
    "driverPrice": 2000,
    "securityDeposit": 4000,
    "freeKm": 250,
    "extraKm": 16,
    "commission": 10,
    "status": "available",
    "trackerId": "",
    "location": "Gavson Business Park, Ghansoli",
    "odometer": "pending",
    "lastService": "pending",
    "tracking": "pending"
  }
];

// Image path resolution: map vehicle brand + model to asset files.
const fleetImageOverrides = {
  // Maruti models
  "maruti swift": "assets/fleet/Maruti Suzuki Swift.png",
  "maruti suzuki swift": "assets/fleet/Maruti Suzuki Swift.png",
  "swift": "assets/fleet/Maruti Suzuki Swift.png",
  "maruti baleno": "assets/fleet/Maruti Suzuki Baleno.png",
  "maruti suzuki baleno": "assets/fleet/Maruti Suzuki Baleno.png",
  "baleno": "assets/fleet/Maruti Suzuki Baleno.png",
  "maruti brezza": "assets/fleet/Maruti Suzuki Brezza.png",
  "maruti suzuki brezza": "assets/fleet/Maruti Suzuki Brezza.png",
  "brezza": "assets/fleet/Maruti Suzuki Brezza.png",
  "maruti dzire": "assets/fleet/Maruti Suzuki Dzire.png",
  "maruti suzuki dzire": "assets/fleet/Maruti Suzuki Dzire.png",
  "dzire": "assets/fleet/Maruti Suzuki Dzire.png",
  "maruti ertiga": "assets/fleet/Maruti Suzuki Ertiga.png",
  "maruti suzuki ertiga": "assets/fleet/Maruti Suzuki Ertiga.png",
  "ertiga": "assets/fleet/Maruti Suzuki Ertiga.png",
  "maruti fronx": "assets/fleet/Maruti Suzuki Fronx.png",
  "maruti suzuki fronx": "assets/fleet/Maruti Suzuki Fronx.png",
  "fronx": "assets/fleet/Maruti Suzuki Fronx.png",
  "maruti grand vitara": "assets/fleet/Maruti Suzuki Grand Vitara.png",
  "maruti suzuki grand vitara": "assets/fleet/Maruti Suzuki Grand Vitara.png",
  "grand vitara": "assets/fleet/Maruti Suzuki Grand Vitara.png",
  "maruti ignis": "assets/fleet/Maruti Suzuki Ignis.png",
  "maruti suzuki ignis": "assets/fleet/Maruti Suzuki Ignis.png",
  "ignis": "assets/fleet/Maruti Suzuki Ignis.png",
  "maruti wagon r": "assets/fleet/Maruti Suzuki WagonR.png",
  "maruti wagonr": "assets/fleet/Maruti Suzuki WagonR.png",
  "maruti suzuki wagon r": "assets/fleet/Maruti Suzuki WagonR.png",
  "maruti suzuki wagonr": "assets/fleet/Maruti Suzuki WagonR.png",
  "wagon r": "assets/fleet/Maruti Suzuki WagonR.png",
  "wagonr": "assets/fleet/Maruti Suzuki WagonR.png",
  "maruti xl6": "assets/fleet/Maruti Suzuki XL6.png",
  "maruti suzuki xl6": "assets/fleet/Maruti Suzuki XL6.png",
  "xl6": "assets/fleet/Maruti Suzuki XL6.png",

  // Hyundai models
  "hyundai exter": "assets/fleet/Hyundai Exter .png",
  "exter": "assets/fleet/Hyundai Exter .png",
  "hyundai aura": "assets/fleet/Hyundai Aura.png",
  "aura": "assets/fleet/Hyundai Aura.png",
  "hyundai creta": "assets/fleet/Hyundai Creta.png",
  "creta": "assets/fleet/Hyundai Creta.png",
  "hyundai i20": "assets/fleet/Hyundai i20.png",
  "i20": "assets/fleet/Hyundai i20.png",
  "hyundai verna": "assets/fleet/Hyundai Aura.png",
  "verna": "assets/fleet/Hyundai Aura.png",
  "hyundai venue": "assets/fleet/Hyundai Creta.png",
  "venue": "assets/fleet/Hyundai Creta.png",

  // Tata models
  "tata altroz": "assets/fleet/Tata Altroz .png",
  "altroz": "assets/fleet/Tata Altroz .png",
  "tata nexon": "assets/fleet/Tata Nexon.png",
  "nexon": "assets/fleet/Tata Nexon.png",
  "tata punch": "assets/fleet/Tata Punch.png",
  "punch": "assets/fleet/Tata Punch.png",
  "tata safari": "assets/fleet/Tata Safari.png",
  "safari": "assets/fleet/Tata Safari.png",
  "tata harrier": "assets/fleet/Tata Safari.png",
  "harrier": "assets/fleet/Tata Safari.png",

  // Mahindra models
  "mahindra 7xo": "assets/fleet/Mahindra 7XO.png",
  "mahindra xuv 7xo": "assets/fleet/Mahindra 7XO.png",
  "mahindra xuv7xo": "assets/fleet/Mahindra 7XO.png",
  "7xo": "assets/fleet/Mahindra 7XO.png",
  "xuv 7xo": "assets/fleet/Mahindra 7XO.png",
  "mahindra 3xo": "assets/fleet/Mahindra 7XO.png",
  "mahindra xuv 3xo": "assets/fleet/Mahindra 7XO.png",
  "mahindra xuv3xo": "assets/fleet/Mahindra 7XO.png",
  "3xo": "assets/fleet/Mahindra 7XO.png",
  "xuv 3xo": "assets/fleet/Mahindra 7XO.png",
  "mahindra xuv700": "assets/fleet/Mahindra XUV700 .png",
  "xuv700": "assets/fleet/Mahindra XUV700 .png",
  "mahindra xuv 700": "assets/fleet/Mahindra XUV700 .png",
  "mahindra scorpio n": "assets/fleet/Mahindra Scorpio N.png",
  "scorpio n": "assets/fleet/Mahindra Scorpio N.png",
  "mahindra scorpio": "assets/fleet/Mahindra Scorpio N.png",
  "scorpio": "assets/fleet/Mahindra Scorpio N.png",
  "mahindra bolero neo": "assets/fleet/Mahindra Scorpio N.png",
  "bolero neo": "assets/fleet/Mahindra Scorpio N.png",
  "mahindra bolero": "assets/fleet/Mahindra Scorpio N.png",
  "bolero": "assets/fleet/Mahindra Scorpio N.png",
  "mahindra thar": "assets/fleet/Mahindra Thar.png",
  "thar": "assets/fleet/Mahindra Thar.png",
  "mahindra thar roxx": "assets/fleet/Thar Roxx.avif",
  "thar roxx": "assets/fleet/Thar Roxx.avif",
  "mahindra xuv500": "assets/fleet/Mahindra XUV500.png",
  "xuv500": "assets/fleet/Mahindra XUV500.png",

  // Toyota models
  "toyota glanza": "assets/fleet/Toyota Glanza.png",
  "glanza": "assets/fleet/Toyota Glanza.png",
  "toyota innova crysta": "assets/fleet/Toyota Innova Crysta.png",
  "innova crysta": "assets/fleet/Toyota Innova Crysta.png",
  "toyota innova hycross": "assets/fleet/Toyota Innova Crysta.png",
  "innova hycross": "assets/fleet/Toyota Innova Crysta.png",
  "toyota innova": "assets/fleet/Toyota Innova Crysta.png",
  "innova": "assets/fleet/Toyota Innova Crysta.png",
  "toyota rumion": "assets/fleet/Toyota Rumion.png",
  "rumion": "assets/fleet/Toyota Rumion.png",
  "toyota urban cruiser": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "toyota urban cruiser taisor": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "urban cruiser taisor": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "urban cruiser": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "toyota taisor": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "taisor": "assets/fleet/Toyota Urban Cruiser Taisor .png",
  "toyota fortuner legender": "assets/fleet/Toyota Innova Crysta.png",
  "fortuner legender": "assets/fleet/Toyota Innova Crysta.png",
  "toyota fortuner": "assets/fleet/Toyota Innova Crysta.png",
  "fortuner": "assets/fleet/Toyota Innova Crysta.png",

  // Honda, Skoda, VW, Kia, MG, BMW
  "honda amaze": "assets/fleet/Hyundai Aura.png",
  "amaze": "assets/fleet/Hyundai Aura.png",
  "honda city": "assets/fleet/Hyundai Aura.png",
  "city": "assets/fleet/Hyundai Aura.png",
  "skoda slavia": "assets/fleet/BMW 520D.png",
  "slavia": "assets/fleet/BMW 520D.png",
  "volkswagen virtus": "assets/fleet/BMW 520D.png",
  "virtus": "assets/fleet/BMW 520D.png",
  "kia seltos": "assets/fleet/Hyundai Creta.png",
  "seltos": "assets/fleet/Hyundai Creta.png",
  "kia sonet": "assets/fleet/Hyundai Creta.png",
  "sonet": "assets/fleet/Hyundai Creta.png",
  "kia carens": "assets/fleet/Kia Carens.png",
  "carens": "assets/fleet/Kia Carens.png",
  "mg hector": "assets/fleet/Tata Safari.png",
  "hector": "assets/fleet/Tata Safari.png",
  "jeep compass": "assets/fleet/Jeep Compass.png",
  "compass": "assets/fleet/Jeep Compass.png",
  "bmw 520d": "assets/fleet/BMW 520D.png",
  "520d": "assets/fleet/BMW 520D.png",
  "bmw": "assets/fleet/BMW.png",
  "mercedes": "assets/fleet/BMW 520D.png",
  "mercedes-benz": "assets/fleet/BMW 520D.png"
};

function findFleetImageOverride(key) {
  if (!key) return null;
  const clean = String(key).trim().toLowerCase().replace(/\s+/g, " ");
  if (fleetImageOverrides[clean]) return fleetImageOverrides[clean];
  const noSpace = clean.replace(/[\s\-_]+/g, "");
  for (const [k, v] of Object.entries(fleetImageOverrides)) {
    if (k.replace(/[\s\-_]+/g, "") === noSpace) return v;
  }
  return null;
}

function fleetImagePath(vehicle) {
  if (!vehicle) return "assets/fleet/BMW.png";
  if (typeof vehicle === "string") {
    if (vehicle.startsWith("http") || vehicle.startsWith("/api/media/")) return vehicle;
    if (vehicle.startsWith("assets/fleet/")) {
      const baseName = vehicle.replace(/^assets\/fleet\//, "").replace(/\.(png|jpg|jpeg|webp|avif)$/i, "").trim();
      const ov = findFleetImageOverride(baseName);
      if (ov) return encodeURI(ov);
      return encodeURI(vehicle);
    }
    const ov = findFleetImageOverride(vehicle);
    if (ov) return encodeURI(ov);
    return `assets/fleet/BMW.png`;
  }

  // If vehicle has an uploaded media ID / external URL, use it
  if (Array.isArray(vehicle.gallery) && vehicle.gallery[0]) {
    const first = vehicle.gallery[0];
    if (first.startsWith("/api/media/") || first.startsWith("http")) {
      return first;
    }
  }
  if (vehicle.imageUrl && (vehicle.imageUrl.startsWith("/api/media/") || vehicle.imageUrl.startsWith("http"))) {
    return vehicle.imageUrl;
  }

  const brand = (vehicle.brand || "").trim();
  const model = (vehicle.model || "").trim();
  const fullName = `${brand} ${model}`.trim();

  const ov = findFleetImageOverride(fullName) ||
    findFleetImageOverride(model) ||
    (brand.toLowerCase() === "maruti" ? findFleetImageOverride(`Maruti Suzuki ${model}`) : null);

  if (ov) return encodeURI(ov);

  return "assets/fleet/BMW.png";
}

function getFleetVehicle(query) {
  if (!query || query === "undefined" || query === "null") return fleetVehicles[0] || null;
  const q = String(query).trim().toLowerCase();
  return (
    fleetVehicles.find(
      (v) =>
        (v.id && v.id.toLowerCase() === q) ||
        (v.slug && v.slug.toLowerCase() === q) ||
        (v.regNo && v.regNo.toLowerCase() === q) ||
        `${v.brand} ${v.model}`.toLowerCase() === q ||
        `${v.brand}-${v.model}`.toLowerCase().replace(/\s+/g, "-") === q ||
        v.brand.toLowerCase() === q ||
        v.model.toLowerCase() === q
    ) || fleetVehicles[0] || null
  );
}

if (typeof window !== "undefined") {
  window.fleetImagePath = fleetImagePath;
  window.fleetVehicles = fleetVehicles;
  window.getFleetVehicle = getFleetVehicle;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = { fleetVehicles, fleetImagePath, getFleetVehicle };
}
