const esc = (v) =>
  String(v ?? "").replace(
    /[&<>"']/g,
    (c) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#039;",
      })[c],
  );
const money = (v) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(
    Number(v || 0),
  );
const dt = (v) =>
  v
    ? new Date(v).toLocaleString("en-IN", {
        dateStyle: "medium",
        timeStyle: "short",
        timeZone: "Asia/Kolkata",
      })
    : "-";
function buildInvoiceHtml(i) {
  const c = i.customer || {},
    v = i.vehicle || {},
    r = i.rental || {},
    ch = i.charges || {},
    d = i.securityDeposit || {};
  const items = [
    ["Rental", ch.rental],
    ["Driver", ch.driver],
    ["Delivery", ch.delivery],
    ["Protection", ch.protection],
    ["Extra KM", ch.extraKm],
    ["Late fee", ch.lateFee],
    ["Fuel", ch.fuel],
    ["Cleaning", ch.cleaning],
    ["Damage", ch.damage],
    ["Toll / parking", ch.toll],
    ["Other", ch.other],
    ["Discount", -Number(ch.discount || 0)],
  ].filter((x) => Number(x[1] || 0));
  return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4}*{box-sizing:border-box}body{font:12px Arial;color:#142033;margin:0}.head{display:flex;justify-content:space-between;border-bottom:2px solid #142033;padding-bottom:18px}.brand{font-size:24px;font-weight:800;letter-spacing:.12em}.accent{color:#18b9f0}.title{text-align:right}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.card{border:1px solid #dfe7ef;border-radius:14px;padding:13px}.label{text-transform:uppercase;color:#738194;font-size:9px;font-weight:700;margin-bottom:5px}table{width:100%;border-collapse:collapse}th{background:#f3f6f9;text-align:left;padding:9px}td{padding:9px;border-bottom:1px solid #edf1f5}.right{text-align:right}.summary{width:48%;margin-left:auto;margin-top:15px}.grand td{border-top:2px solid #142033;font-size:15px;font-weight:800}.deposit{margin-top:18px;padding:13px;border-radius:14px;background:#f6f9fc}.foot{margin-top:24px;border-top:1px solid #dfe7ef;padding-top:10px;color:#728092;font-size:9px}</style></head><body><div class="head"><div><div class="brand">KRUIZLY<span class="accent">.</span></div><div>${esc(process.env.COMPANY_LEGAL_NAME || "Premium Self-Drive Rentals")}</div></div><div class="title"><h1>${i.type === "FINAL" ? "FINAL INVOICE" : "INVOICE"}</h1><strong>${esc(i.invoiceNumber)}</strong><br>${esc(i.status || "ISSUED")}</div></div><div class="grid"><div class="card"><div class="label">Bill to</div><strong>${esc(c.name || "-")}</strong><br>${esc(c.email || "")}<br>${esc(c.phone || "")}<br>${esc(c.address || "")}</div><div class="card"><div class="label">Booking</div><strong>${esc(i.bookingId || "-")}</strong><br>Invoice date: ${dt(i.invoiceDate)}<br>Payment: ${esc(i.payment?.status || "-")}</div><div class="card"><div class="label">Vehicle</div><strong>${esc(v.name || "-")}</strong><br>${esc(v.registration || "")}<br>${esc(v.category || "")}</div><div class="card"><div class="label">Rental</div>Pickup: ${dt(r.pickupDate)}<br>Return: ${dt(r.returnDate)}<br>${esc(r.duration || "")}</div></div><table><thead><tr><th>Description</th><th class="right">Amount</th></tr></thead><tbody>${items.map((x) => `<tr><td>${esc(x[0])}</td><td class="right">${money(x[1])}</td></tr>`).join("")}</tbody></table><table class="summary"><tr><td>Subtotal</td><td class="right">${money(i.subtotal)}</td></tr><tr><td>Tax</td><td class="right">${money(i.tax)}</td></tr><tr class="grand"><td>Total</td><td class="right">${money(i.total)}</td></tr><tr><td>Paid</td><td class="right">${money(i.amountPaid)}</td></tr><tr><td>Balance</td><td class="right">${money(i.balanceDue)}</td></tr></table><div class="deposit"><strong>Security Deposit</strong><br>Collected: ${money(d.collected)} &nbsp; Deducted: ${money(d.deducted)} &nbsp; Refund: ${money(d.refunded)}</div><div class="foot">${esc(i.notes || "Electronic invoice generated by Kruizly.")}<br>${esc(process.env.COMPANY_ADDRESS || "Mumbai, Maharashtra, India")}</div></body></html>`;
}
module.exports = { buildInvoiceHtml };
