-- ============================================================
-- KRUIZLY MYSQL AUTO_INCREMENT FIX
-- Run this in phpMyAdmin if any table lacks AUTO_INCREMENT
-- ============================================================

ALTER TABLE `admin_users` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `audit_logs` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `bookings` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `contact_messages` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `coupons` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `coupon_usage` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `expenses` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `invoices` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `invoice_items` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `media` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `partner_cars` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `partner_leads` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `payments` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `reviews` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `users` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `vehicles` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `verification` MODIFY `id` INT NOT NULL AUTO_INCREMENT;
